rover:
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 0.5
      scale_linear:
        x: 1.0
      scale_linear_turbo:
        x: 2.0

      axis_angular:
        yaw: 0.5
      scale_angular:
        yaw: 1.0
      scale_angular_turbo:
        yaw: 2.0

      enable_button: 8  # L2 shoulder button
      enable_turbo_button: 10  # L1 shoulder button
